name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    container: debian:bullseye

    
    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev
    - name: make
      run:  make --load 2 V=1 BOARD=qemu-coreboot
      
